/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fnozcorwbnlkdqtsbuye"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZub3pjb3J3Ym5sa2RxdHNidXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNzU4NDIsImV4cCI6MjA4MDk1MTg0Mn0.0jDVlCQ9jyP-K0UpIIsneE4U-3TqP6uzmQiJ-ohq9nM"